"""
Django settings for DGA project.

Generated by 'django-admin startproject' using Django 2.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""
import os
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

STATIC_URL = '/static/'
# 获取当前陪着文件路径的转义路径
# F:/My_Python/DGA_web_RealTimeMonitoring -整合前-ing/ProjectMain/'
# 'F:\\My_Python\\DGA_web_RealTimeMonitoring -整合前-ing\\ProjectMain'
PROJECT_PATH = os.path.abspath(os.path.dirname(__file__))
# 在 PATH基础上再一次dir 之后的带上一级路径
STATIC_ROOT = os.path.join(os.path.dirname(PROJECT_PATH), 'static')
STATICFILES_DIRS = (

    ("css", os.path.join(STATIC_ROOT, 'asserts/css')),
    ("asserts", os.path.join(STATIC_ROOT, 'asserts')),
    ("js", os.path.join(STATIC_ROOT, 'asserts/js')),
    ("BJUI", os.path.join(STATIC_ROOT, 'BJUI')),
    ("layer", os.path.join(STATIC_ROOT, 'layer')),
    ("media", os.path.join(STATIC_ROOT, 'media')),
    ("upload", os.path.join(STATIC_ROOT, 'upload')),
    ("echarts-2.27", os.path.join(STATIC_ROOT, 'echarts-2.27')),
    ("jquery-ui-bootstrap", os.path.join(STATIC_ROOT, 'jquery-ui-bootstrap')),
    ("img", os.path.join(STATIC_ROOT, 'img')),
)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'mvgztwl%eg2k#uns*oo7)dapo8tw)9f7zzqqh+w)&w&$2is$wo'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ProjectMain.RealTimeMonitoring',
    'ProjectMain.utils',
    'ProjectMain.templatetags',

]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
# 出现跨域问题，只添加下面这个设置，解决问题
CORS_ALLOW_HEADERS = ('*')
CORS_ORIGIN_ALLOW_ALL = True

ROOT_URLCONF = 'ProjectMain.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR + "/templates", ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries': {  # Adding this section should work around the issue.
                     'My_tags': 'ProjectMain.templatetags.My_tags',
},

        },
    },
]

WSGI_APPLICATION = 'ProjectMain.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'dgamonitoring',
        'USER': 'root',
        'PASSWORD': '123456',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

DEFAULT_CHARSET = 'UTF-8'
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/
#
X_FRAME_OPTIONS = 'ALLOWALL'
